# Multiprocessing
#-----------------------
MAX_PROC: null
MAX_THREADS: 3

# case params
#---------------------------
#/

# ESN Setting
#---------------------------
n_reservoir: 2048
leakingRate: 1.0
spectralRadius:  0.99
reservoirDensity: 0.2
regressionParameter: 5.0e-2
mode: "auto"
verbose: False

bias_in: 1
bias_out: 1
outputInputScaling: 0
inputScaling: 1
feedbackScaling: 1
inputDensity: 1
noiseLevel_in: 1e-6
noiseLevel_out: 0
extendedStateStyle: "default"
weightGeneration: "uniform"
use_feedback: False

# ESN Data Layout
#---------------------------
dataScaling: 1
trainingLength: 750
testingLength:  700
validationLength: 400
transientTime: 50

# Hyperparameter Grid & Random Search
#---------------------------
nseed: 10                                        
doRandomSearch: False   #random search                                    
nstudy: 100             #random search
use_log_scale: True     #random search

# Specify HP to be studied (first one moving slowest)
study_tuple:                     
  - "regressionParameter"
  - "spectralRadius"
  - "leakingRate_neural"
 
# Specify HP Grid
#NOTE: study_param_list has higher priority than study_param_limits
study_param_limits:               #[val_min, val_max, nval, use_log]   
  - [-4,0,5,True]
  - [0,1.3,12,False]
  - [-4,0,5,True]

# Specify own values for HP Grid
study_param_list:                 #[val1, val2, val3,...] 
  - []
  - []
  - []

  
# Data paths
#---------------------------
path_data:     ''                       
filename_data: ''
path_esn:      ''                          

comment_str: ""
